### ISSUE TITLE
When operating on goerli, "View on Etherscan" links to unlocatable mainnet transactions

### ISSUE THREAD

**Issue by chrishobcroft** [luzzif/rails#4]
# Overview

When running on Goerli testnet, Etherscan links take me to Etherscan's _mainnet_ block explorer, not their _goerli_ block explorer :<(

# Observed Behaviour

1. Load https://goerli-loopring-pay-ui.netlify.app/dashboard and login etc.
![image](https://user-images.githubusercontent.com/2212651/86512141-037bde80-be1d-11ea-8e65-4a3a71b18238.png)

2. Click the "Deposit"
![image](https://user-images.githubusercontent.com/2212651/86512153-1a223580-be1d-11ea-9f23-ac6e45e3ca14.png)

3. Click "View on Etherscan"
![image](https://user-images.githubusercontent.com/2212651/86512168-30c88c80-be1d-11ea-8bd9-d99da403e87a.png)

**_Unexpected Behaviour - this loads up a page at https://etherscan.io_** 

# Expected Behaviour

At step 3, I would expect it to load up a page at https://**goerli**.etherscan.io

**Comment by luzzif** [comment]
Should be fixed now. Could you please confirm? Waiting for a feedback before closing the issue.
